### PR TITLE
Generate patch after text changed

### PR DESCRIPTION
**Pull request by aloscha**

### CODE REVIEW

**Comment by joozek78** [comment]
Why is it needed here? Input element with input event listener has always worked for us

**Comment by aloscha** [comment]
Because the view with autocomplete box is inside Authorization lib. Also When you type some text, patches don't go into server. You have situation: typing some workgroup and you need to click somewhere that server respond with fit groups - I changed it into after each keypress server respond with fit groups.

**Comment by mmnosek** [comment]
True, but it worked without that before. Maybe problem is somewhere else?

**Comment by alshakero** [comment]
@mmnosek @joozek78 I guess that's because there is a two-way binding that is capturing the key event and preventing propogation (because jsonpatch relies on the event to dirtycheck). [This is a Polymer _feature_](https://www.polymer-project.org/1.0/docs/devguide/events). 

image

I suggest that you don't spend time on this. We're testing the Proxy Palindrom version and it's looking great with KitchenSink, it will fix all these issues.

**Comment by aloscha** [comment]
tnx @alshakero

**Comment by mmnosek** [comment]
@alshakero so should we just wait for the update? When might it be available more or less? Week? Month? Year?  :)

**Comment by alshakero** [comment]
@mmnosek no no, I just mean that I'd keep @aloscha's fix for the mean time, even if it looks dirty, we'll be able to remove it all together soon. 

We're finishing soon (100% less than a month), but I wouldn't like you to wait, so I suggest to keep this hack, and I'll ping you to remove it when done.

**Comment by mmnosek** [comment]
It's not a authorization lib problem. `::input` listener doesn't work anywhere now.

**Comment by mmnosek** [comment]
@aloscha - the problem is in our javascript, neither in authorization lib nor polymer :) Closing without merge.

**Pull request closed without merging**
